name = "your-worker-name"
main = "src/index.ts"
account_id = "2343e56986ee37406d55464b753fd0d5"
route = ""
workers_dev = true
compatibility_date = "2023-04-11"

[build]
command = "npm install && npm run download:manifest && npm run build"

[vars]
ORIGIN_URL = "69895ea401.nxcli.net"
